# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cleintapi:
    image: clientservice
    container_name: clientservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
networks:
  default:
    external:
        name: jar-container-network

